#!/usr/bin/env ruby
# encoding: UTF-8
# exe/lucian

# $: is just a shortcut for $LOAD_PATH. __FILE__ is the relative 
#   path to the script. This adds the current script directory 
#   to the load path

this_file = Pathname.new(__FILE__).realpath
$:.unshift File.expand_path("../../lib", this_file)
require 'lucian'
require 'rspec/core'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: lucian [options]"

  opts.on("-i", "--init", "Initialize Lucian environment") do |v|
    options[:init] = v
    Lucian::Initiator.init
  end

  opts.on("-eSTRING", "--example=STRING", "Run examples whose full nested names include STRING") do |v|
    (options[:example] ||= []) << Regexp.compile(Regexp.escape(v))
  end
end.parse!

if options[:init].nil?
  lucian = Lucian::Engine.new(nil, options[:example])
  begin
    lucian.run
  ensure
    lucian.shutdown
  end
end
